server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki-stdout:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/*-json.log

      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: '/(.*)'

      - source_labels: [__meta_docker_container_image]
        target_label: image

      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service

      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: compose_project

    pipeline_stages:
      - docker: {}

      - json:
          expressions:
            level: level
            msg: message
            logger: logger
            thread: thread

      - labels:
          level:
          compose_service:
          compose_project:

      - output:
          source: msg